### ISSUE TITLE
460MHz in US is shown as "Medical Telemetry"

### ISSUE THREAD

**Issue by isaacgerg** [Arrin-KN1E/SDRsharpbandplans#10]
This is ambulance and police bands in the US.

**Comment by Arrin-KN1E** [comment]
Thanks for the correction! I will fix other allocations to align with this source: ( https://www.fcc.gov/public-safety/public-safety-and-homeland-security/policy-and-licensing-division/public-safety-spectrum ) and close this issue when the corrections are committed.

**Comment by Arrin-KN1E** [comment]
I have updated the file. I will leave this issue open for a few days for comment, then close it if there are no more comments.

**Comment by isaacgerg** [comment]
You also have 452.675 as a railroad frequency but I think this is a business frequency as I see a lot of taxi traffic on it.

**Comment by isaacgerg** [comment]
You can use this link to search by frequency for US allocations: https://fjallfoss.fcc.gov/General_Menu_Reports/engineering_search.cfm?accessible=NO

**Comment by Arrin-KN1E** [comment]
452.675MHz falls under private land mobile radio services, which include public safety agencies, utilities, railroads, manufacturers, and businesses: [FCC Table]( https://transition.fcc.gov/oet/spectrum/table/fcctable.pdf#page=29 ) I only named 452.675 and surrounding frequencies as railroad, since it is so close to the railroad telemetry frequencies, such as EOTD: https://www.sigidwiki.com/wiki/End_of_Train_Device_(EOTD) . Private Land Mobile Radio Services is a bit generic of a name for my taste, so I usually try to give them a definitive name, however it appears it would be best to name them as such to avoid confusion in the future in the more crowded areas. (e.g. 452.675MHz also appears to be a hospital trunking frequency: https://www.radioreference.com/apps/db/?sid=2584 ) So, I will name the more crowded areas the generic name Private Land Mobile when I can work on it again.    

I seem to not be able to get the Site / Market / Frequency Query page to work. I likely just don't know how to use it. Do you have an example I can use?

**Comment by isaacgerg** [comment]
> I seem to not be able to get the Site / Market / Frequency Query page to work. I likely just don't know how to use it. Do you have an example I can use?

Sure. For state, select PA. For frequency, use  452.675 for begin and end.  Then hit Submit Query.  The website is slow but upon its loading, you should see "Altoona Area School District" come up as the first result.

**Comment by isaacgerg** [comment]
It would be nice to be able to edit or make notes on the band plan in sdr sharp so as one begins to research frequencies for their area, they can further customize the display.

**Comment by Arrin-KN1E** [comment]
Oh okay, I was just requesting a bit too much info, and it was timing out. Makes sense. Great tool, thanks! I'll go back over some questionable allocations.  
Yeah, it would be nice to have everything available on the FFT display; like double click to get banner properties. I'm sure something like that is possible, it's just above my pay grade. I don't know but it looks like the people over at [SDR++]( https://github.com/AlexandreRouma/SDRPlusPlus ) might have something similar to what you describe. Only thing like that on SDR# that I'm aware of is the frequency manager. Or, worst case, have the XML file open with the notes in it.
