### ISSUE TITLE
Propagation Test in 13.9 MHz is missing MARS

### ISSUE THREAD

**Issue by isaacgerg** [Arrin-KN1E/SDRsharpbandplans#14]
I'm uncertain where the "propagation test" moniker came from that you list.  However, i do know that the primary MARS frequency is 13.927MHz. There are a few other MARS bands also.  Depending on the source of the current moniker, you might find it useful to remove it and simply list the MARS bands.

Ref: http://www.marsphonepatch.net/operation-faq

**Comment by Arrin-KN1E** [comment]
@isaacgerg Thanks for brining that to my attention! The 'Propagation Test' moniker came from US340 footnote in the FCC Table of Frequency Allocations ( https://transition.fcc.gov/oet/spectrum/table/fcctable.pdf ). I am planning an update to the bandplans that will remove these placeholder allocations, since they are no longer befitting to the purpose of a detailed bandplan. 
I will probably publish a small update soon, addressing all listed issues in the repository before the larger update.

**Comment by Arrin-KN1E** [comment]
@isaacgerg 7.6335MHz, 11.407MHz, and 13.927MHz have been added. If you have any other comments/ fixes about this issue let me know, as I will close this issue as of 1 week after last activity. As of now, I will add any other MARS frequencies I can find in the next update.
